name: CI

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 14.4
  POSTGRESQL_DB: skecorp
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.4
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          DATA_SOURCE_USERNAME: ${{ env.POSTGRESQL_USER }}
          POSTGRESQL_USER: ${{ env.POSTGRESQL_USER }}
          DATA_SOURCE_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
          POSTGRESQL_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Change maven wrapper permissions
        run: chmod +x ./mvnw
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend