name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 14.4
  POSTGRESQL_DB: postgres 
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  DATA_SOURCE_USERNAME: postgres
  DATA_SOURCE_PASSWORD: password
  DB_HOST: //localhost:5432/postgres
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Change maven wrapper permissions
        run: chmod +x ./mvnw
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend