name: CICD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  # Java
  JAVA_VERSION: 17
  # DockerHub
  DOCKER_HUB_USERNAME: skelevel
  # AWS & Elastic Bean Stalk
  AWS_REGION: ap-south-1
  EB_ENVIRONMENT_NAME: Skecorpstudentmgmtapp-env
  EB_APPLICATION_NAME: skecorp-student-mgmt-app
  EB_DEPLOYMENT_PACKAGE: student-mgmt/docker-compose.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.10
        env:
          POSTGRES_DB: ${{ secrets.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ secrets.DATA_SOURCE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATA_SOURCE_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CICD ongoing... :eyes:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Change maven wrapper permissions
        run: chmod +x ./mvnw
      
      - name: Maven Clean Package and Push to Dockerhub
        run: |
          ./mvnw --no-transfer-progress clean package \
            -P build-frontend \
            -P jib-push-to-dockerhub \
              -Dapp.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}} \
              -Dapp.image.name=spring-react-fullstack \
              -Dapp.image.DB_HOST=${{secrets.DB_HOST}}/${{ secrets.POSTGRESQL_DB }} \
              -Dapp.image.DATA_SOURCE_USERNAME=${{secrets.DATA_SOURCE_USERNAME}} \
              -Dapp.image.DATA_SOURCE_PASSWORD=${{secrets.DATA_SOURCE_PASSWORD}}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':white_check_mark: pushed edcsu/student-mgmt:${{steps.build-number.outputs.BUILD_NUMBER}} to docker hub... https://hub.docker.com/repository/docker/edcsu/student-mgmt'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update and commit app version in docker-compose.yaml
        run: |
          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
          echo -e "Current student-mgmt/docker-compose.yml\n$(cat student-mgmt/docker-compose.yml)"
          sed -i -E 's_(edcsu/student-mgmt:)([^"]*)_\1'${BUILD_NUMBER}'_' student-mgmt/docker-compose.yml
          echo -e "Current student-mgmt/docker-compose.yml\n$(cat student-mgmt/docker-compose.yml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add student-mgmt/docker-compose.yml
          git commit -m "new app version: ${BUILD_NUMBER}"
          git push

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':elasticbeanstalk: :aws: Deployment started... :grimacing: :crossed_fingers:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: Version ${{steps.build-number.outputs.BUILD_NUMBER}} deployed via github actions ${{ github.sha }}
          wait_for_deployment: 60
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':tada: :arrow_right: http://skecorpstudentmgmtapp-env.eba-zghmzyyu.ap-south-1.elasticbeanstalk.com/'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()